include $(LITEOSTOPDIR)/../../drivers/adapter/khdf/liteos/lite.mk
MODULE_NAME := $(notdir $(shell pwd))
#LOCAL_INCLUDE := -I $(LITEOSTOPDIR)/
LOCAL_SRCS := fw_cfg.c
LOCAL_CFLAGS += $(LOCAL_INCLUDE)

include $(HDF_DRIVER)
