include $(LITEOSTOPDIR)/../../drivers/hdf/lite/lite.mk
MODULE_NAME := $(notdir $(shell pwd))
#LOCAL_INCLUDE := -I $(LITEOSTOPDIR)/
LOCAL_SRCS := cfiflash.c hdf_cfi.c
LOCAL_CFLAGS += $(LOCAL_INCLUDE)

include $(HDF_DRIVER)
